
mex Interface.cpp grad_desc_async_KroMagnon.cpp ...
 grad_desc_async_S2VRG.cpp grad_desc_async_ASAGA.cpp svm.cpp grad_desc_async_VRSGD.cpp...
  logistic.cpp least_square.cpp blackbox.cpp regularizer.cpp -largeArrayDims -g
